### Listar todos los libros...arrancar el servidor con php -S localhost:8001
GET http://localhost:8001/index.php

### Agregar un libro
POST http://localhost:8001/index.php
Content-Type: application/json

{
  "title": "1984",
  "author": "George Orwell",
  "genre": "Dystopian",
  "published_year": 1949
}

### Actualizar un libro
PUT http://localhost:8001/index.php
Content-Type: application/json

{
  "id": 1,
  "title": "Animal Farm",
  "author": "George Orwell",
  "genre": "Political Satire",
  "published_year": 1945
}

### Eliminar un libro
DELETE http://localhost:8001/index.php
Content-Type: application/json

{
  "id": 1
}
